### ISSUE TITLE
Add NGC support

### ISSUE THREAD

**Issue by danbucholtz** [apoterenko/angular2-dynamic-component#11]
This library is not compatible with the Angular AoT compiler.

Please compile using NGC and leave in the `.metadata.json` files.

See this comment for more info.

https://github.com/driftyco/ionic-app-scripts/issues/145#issuecomment-254256252

Thanks,
Dan

**Comment by apoterenko** [comment]
Hi, Dan!

I've built the package using ngc, thanks for your tips

**Comment by danbucholtz** [comment]
@apoterenko,

To be clear, this fails when a consuming library builds it with `ngc` since the package does not have the `.metadata.json` files included. We (Ionic) got burned by this when we first started testing as it's not documented well.

Thanks,
Dan
