### ISSUE TITLE
Cannot assign to a reference or variable! 

### ISSUE THREAD

**Issue by jorgepluna** [apoterenko/angular2-dynamic-component#12]
Fantastic product you developed (THANKS!). I have the following situation.

Using input in my template for the DynamicContext data.  
<  input type="text"  [(ngModel)]="user" name="user"  **#user="ngModel"** [rangeLength]="[5, 9]" (ngModelChange)="onChange($event)"   /> 
  < p *ngIf="username?.errors?.rangeLength">rangeLength error</p>  (Can you please help??)
 ** #user = "ngModel"  t**hrows error "Cannot assign to a reference or variable! "**********

vendor.bundle.js:21405 EXCEPTION: Uncaught (in promise): Error: Cannot assign to a reference or variable!ErrorHandler.handleError @ vendor.bundle.js:21405
vendor.bundle.js:21410 ORIGINAL STACKTRACE:ErrorHandler.handleError @ vendor.bundle.js:21410
vendor.bundle.js:21411 Error: Uncaught (in promise): Error: Cannot assign to a reference or variable!

<input type="text"  [(ngModel)]="user" name="user"  #user="ngModel" [rangeLength]="[5, 9]" (ngModelChange)="onChange($event)"   /> 
  < <p *ngIf="username?.errors?.rangeLength">rangeLength error</p>

**Comment by jorgepluna** [comment]
Thank you for your response. 

I tried adding the suggested modules to extraModules as below. Unfortunately I continue getting the same error.  Any other suggestions? It would be fantastic to have the capability of two way binding. Your modules are great!

core.umd.js:3462EXCEPTION: Uncaught (in promise)**: Error: Cannot assign to a reference or variable!**

import { FormsModule, ReactiveFormsModule, FormBuilder, Validators, FormControl } from '@angular/forms';
import { InnerModule } from './dynamic.module';
import { DynamicContext } from '../appclasses/DynamicContextClass';
import { CustomFormsModule } from 'ng2-validation'

public value: string = "";
    public user: string = "user"
    inputData: IComponentInputData = {
        value: this.value,
        user: this.user
    };

    private extraModules = [FormsModule, ReactiveFormsModule, CustomFormsModule];
    private componentTemplate: string = `
 <form #demoForm="ngForm" (ngSubmit)="onSubmit(demoForm)" novalidate>
  
 
 < <input type="text"  [(ngModel)]="user" name="user"  #user="ngModel" [rangeLength]="[5, 9]" (ngModelChange)="onChange($event)"   /> 
  < <p *ngIf="username?.errors?.rangeLength">rangeLength error</p>

**Comment by apoterenko** [comment]
This is not DynamicComponent issue.

Try to rename #user -> #userAlias
