### ISSUE TITLE
Supplied parameters do not match any signature of call target

### ISSUE THREAD

**Issue by scottopolis** [apoterenko/angular2-dynamic-component#13]
Here's another ngc error for you :)

[14:27:16]  Error: Error at /.tmp/pages/custom-pages/custom-page.ngfactory.ts:290:40
[14:27:16]  Supplied parameters do not match any signature of call target.
[14:27:16]  ngc failed
[14:27:16]  ionic-app-script task: "build"
[14:27:16]  Error: Error

This is caused by adding a constructor to my main class.  If I remove the constructor, the error goes away.  Here's my code:

**Works:**

```
@Component({
  template: `<DynamicComponent [componentTemplateUrl]="templateUrl"></DynamicComponent>`
})
export class CustomPage {
	templateUrl: string;

	ngOnInit() {
		this.templateUrl = 'mytemplate.html';
	}

}
```

**Does not work:**

```
import {NavParams} from 'ionic-angular';

@Component({
  template: `<DynamicComponent [componentTemplateUrl]="templateUrl"></DynamicComponent>`
})
export class CustomPage {

	templateUrl: string;

	constructor( public navParams: NavParams ) {
	}

	ngOnInit() {
		this.templateUrl = 'mytemplate.html';
	}

}
```

You should be able to reproduce this even without Ionic, just by adding a constructor with an argument.  Any help is appreciated.

Thanks!

**Comment by paulodoux** [comment]
you forgot

`import { OnInit} from '@angular/core';`
and
`export class CustomPage implements OnInit `

**Comment by scottopolis** [comment]
Added that, still getting the same error.

**Comment by apoterenko** [comment]
I have no experience of using ionic, sorry :(

**Comment by apoterenko** [comment]
I'm sorry, but this is not dynamic component error
