### ISSUE TITLE
Template does not have this expression

### ISSUE THREAD

**Issue by jorgepluna** [apoterenko/angular2-dynamic-component#14]
Can't bind to 'componentModules' since it isn't a known property of 'template'. ("
 <template dynamic-component
          [ERROR ->][componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template>

<template dynamic-component
          [componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template> 

I am getting error that "template" does not contain componentModules. Where is template? What happened with the old documentation? Now it is very hard to understand this version.

Thanks

**Comment by apoterenko** [comment]
import {DynamicComponentModule} from 'angular2-dynamic-component/index';

@NgModule({
    imports: [DynamicComponentModule]
})

?

**Comment by jorgepluna** [comment]
Same error:
Apparently "template " directive does not have a property called "componentModules'. Is template a new way of using your API? before I used "Dynamiccomponent ......".

my code: 

import { DynamicComponentModule } from 'angular2-dynamic-component/index';
@Component({
    selector: 'creategraphobjectchildl1-component',
    template: `
  <template 
          [componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template>
  `,
})


public value: string = "";
    public user: string = "user"
    extraTemplate = `<DynamicComponent [componentTemplate]='"<span>Dynamic inside dynamic!</span>"'></DynamicComponent>`;
    extraModules = [DynamicComponentModule ]; 

Thanks a lot!

Can't bind to 'componentModules' since it isn't a known property of 'template'. ("<template dynamic-component
          [ERROR ->][componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template>
  "): CreateGraphObjectComponent@1:10

**Comment by apoterenko** [comment]
@Component({
selector: 'creategraphobjectchildl1-component',
template:  <template **dynamic-component** [componentModules]="extraModules" [componentTemplate]='extraTemplate'></template> ,
})

**Comment by apoterenko** [comment]
@Directive({
	selector: DYNAMIC_SELECTOR,
})
export class DynamicDirective extends DynamicBase {
...
	@Input() componentModules: Array<any>;

**Comment by jorgepluna** [comment]
Thanks for your answer! i keep getting error .  Can you expand on how to use the Directive? 

Code;@Component({
    selector: 'creategraphobject-component', 
    template: `<template dynamic-component
          [componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template>
  `,
})


Can't bind to 'componentModules' since it isn't a known property of 'template'

**Comment by apoterenko** [comment]
See 
https://github.com/apoterenko/angular2-dynamic-component/commit/4c9f4123ee523dfdda812d5aeaf234db08fdff47

**Comment by jorgepluna** [comment]
Now worked. Thanks!

What happened with the older version?

**Comment by apoterenko** [comment]
I have only added support of Directive
