### ISSUE TITLE
Usage with ionic

### ISSUE THREAD

**Issue by akshatster** [apoterenko/angular2-dynamic-component#15]
First off thanks so much for making this module. It makes life so much easier instead of building out the constant changes over the past few RCs.

I'm having a bit of trouble using it with Ionic, i'm not sure if Ionic has anything to do with it:

```
import { AboutPage } from "../../pages/about/about"

@Component({
  selector: 'firststep-home-overcard',
  templateUrl: 'home-overcard.html'
})
export class Home {
  extraTemplate = `<page-about></page-about>`;
  extraModules = [];
```

And my html
```
<template dynamic-component
          [componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template>
```

With this I get the error `'page-about' is not a known element:`.

If I add `AboutPage` to `extraModules`:

```
  extraModules = [AboutPage];
```

The error becomes: Error: Unexpected directive 'AboutPage' imported by the module 'dynamicComponentModule'

Also in case this is helpful the import in the NgModule:

```
  imports: [
    IonicModule.forRoot(FirstStep),
    DynamicComponentModule
  ],
```

Is there something more that needs to be done? I'm following the example set out on the README

**Comment by apoterenko** [comment]
You should wrap your custom Directive

@NgModule {
     declarations: [AboutPage],
    exports: [AboutPage]
} 
AboutPageWrapperModule {}

extraModules = [
  AboutPageWrapperModule
]

?
