### ISSUE TITLE
How to share values from Dynamic inside Dynamic?

### ISSUE THREAD

**Issue by jorgepluna** [apoterenko/angular2-dynamic-component#16]
Fantastic tool you created. 

Now I have a situation when I need to get the value of an input from a Dynamic component inside a Dynamic component. 

 <template dynamic-component
              [componentContext]="context" 
              [componentModules]="extraModules"
              [componentTemplate]= "extraTemplate"></template> 

Inside extraTemplate:

  <p-dialog header="people.address.jorge" [(visible)]="display" 
           resizable = false    closable = true responsive = true   width = 400  closable = "true" >
              <DynamicComponent 

                                [componentContext]="context"  
                                [componentTemplate]="extraTemplate3" 
                                [componentModules]="extraModules"></DynamicComponent>
                               
  </p-dialog>

Want to get an input data from extraTemplate3 into a value in extraTemplate.

Any suggestions? Samples would be great! Thanks.. 

Note: Planing to use your software to help Africans develop software.

**Comment by apoterenko** [comment]
See https://github.com/apoterenko/angular2-dynamic-component/commit/78daefc2e3ced81f47f3d5269fb8aeb189a90ffd

Demo works fine)

**Comment by apoterenko** [comment]
See demo

**Comment by apoterenko** [comment]
See demo

**Comment by apoterenko** [comment]
See https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts
