### ISSUE TITLE
Doesn't work with AOT

### ISSUE THREAD

**Issue by ColinFrick** [apoterenko/angular2-dynamic-component#17]
The current version doesn't work with AOT.

If I compile it with aot and run it in the browser the output is just empty:
```
<!--template bindings={}--><br _ngcontent-whe-1="">

Inner dynamic value (root level): inner value<br _ngcontent-whe-1="">

<dynamiccomponent _ngcontent-whe-1=""></dynamiccomponent>
```

I used qdouble/angular-webpack2-starter and your sample code to test it.

**Comment by apoterenko** [comment]
Thanks for your request!

I will fix it as soon as possible

**Comment by apoterenko** [comment]
Yeah, see https://github.com/angular/angular/issues/11780

**Comment by apoterenko** [comment]
Or we can use workaround using @experimental bootstrapModuleFactory 
	
	 /**
     * Creates an instance of an `@NgModule` for the given platform
     * for offline compilation.
     * ...
     * @experimental APIs related to application bootstrap are currently under review.
     */
    bootstrapModuleFactory

**Comment by scottopolis** [comment]
Hi, is there a way to make this work with AOT yet?

Thanks

**Comment by apoterenko** [comment]
https://github.com/angular/angular/issues/11780
