### ISSUE TITLE
Duplicate dynamiccomponent node

### ISSUE THREAD

**Issue by KeksKlip** [apoterenko/angular2-dynamic-component#18]
Template like 
`
<DynamicComponent 
                            [componentTemplate]="template"
                            [componentContext]="context" 
                            [componentModules]="dynamicExtraModules"></DynamicComponent>
`
is rendered with the second dynamiccomponent node, but with empty context value.

![dynamyccomponent-duplacates](https://cloud.githubusercontent.com/assets/576345/20626860/44bea804-b314-11e6-9926-d9a0a539558a.png)

**Comment by apoterenko** [comment]
Try use directive?

<template dynamic-component
          [componentModules]="extraModules"
          [componentTemplate]='extraTemplate'></template>

?

**Comment by KeksKlip** [comment]
I've tried it already

`
<template dynamic-component  [componentTemplate]="tab?.detailViews[1].template"
                    [componentContext]="doc" [componentModules]="dynamicExtraModules"></template>
`

 dynamicExtraModules = [DynamicComponentModule, FormsModule];

tab and doc are data I get from MongoDB. 

On your demo I don't have duplicates.

**Comment by apoterenko** [comment]
Please provide your source code

**Comment by KeksKlip** [comment]
Here is my code https://github.com/KeksKlip/MyCRMUi
I use it in MyCRMUi/src/app/account-detail/account-detail.component.html

**Comment by apoterenko** [comment]
Thanks for your request! Try use 1.1.0

This is a regress..

https://github.com/apoterenko/angular2-dynamic-component/commit/657d8ddf37c331d3565d5b83a0eab6ccb2425e1f

**Comment by KeksKlip** [comment]
Thanks.
Updated to the last version.
Works well
