### ISSUE TITLE
Angular TS imports need to upgrade to RC6 changes

### ISSUE THREAD

**Issue by thegreenpizza** [apoterenko/angular2-dynamic-component#2]
Because of breaking changes in RC6, switching to UMD modules causes this project to break. In order to fix, follow the steps here: https://github.com/angular/angular/blob/master/CHANGELOG.md#bootstrap-changes:

```
Before:

import {TestInjector, getTestInjector} from '@angular/core/testing';
After:

import {TestBed, getTestBed} from '@angular/core/testing';
```

This should be quite easy to do just updating the imports inside of DynamicComponent.ts.

**Comment by thegreenpizza** [comment]
I imagine the change will look something like this:

https://github.com/thegreenpizza/angular2-dynamic-component/commit/a288aa812d8a9191718b6323ec78e2f9a89cdeb1

**Comment by thegreenpizza** [comment]
I realize playing with this a bit that the reason you are doing this is because you are using nonpublic angular APIs. Perhaps there's a way to reconcile the systemjs loading with the APIs that are not part of the umd bundles.

**Comment by apoterenko** [comment]
Please check 0.0.39 build. It should work fine without unnecessary imports of the internal modules.

**Comment by thegreenpizza** [comment]
Thanks, that fixed the issues.

**Comment by apoterenko** [comment]
Ok, I have closed the issue
