### ISSUE TITLE
templateUrl with a local path

### ISSUE THREAD

**Issue by SamuelMarks** [apoterenko/angular2-dynamic-component#20]
Use-case is static loading of local paths:

    <h3>stuff</h3>
    <template dynamic-component [componentTemplateUrl]='"src/app/foo/foo0.component.html"'>
    </template>

    <template dynamic-component [componentTemplateUrl]='"src/app/foo/foo1.component.html"'>
    </template>

    <template dynamic-component [componentTemplateUrl]='"src/app/foo/foo2.component.html"'>
    </template>

I'm thinking of this as a precompilation stage—like macros in C/C++, Qt's fancy layer &etc.—so it will replace each of those lines with the actual HTML content of the relevant components just before Angular2/webpack compiles everything.

What are your thoughts?

<may be related https://github.com/apoterenko/angular2-dynamic-component/issues/17>

**Comment by apoterenko** [comment]
I think this is a useful feature.
But.. you can inline template explicitly via "require" and the Webpack preprocessors

@Component({
  template: `                                        
    <template dynamic-component[componentTemplate]="inlineTemplate"></template><br>
  `
})
export class AppComponent {
   inlineTemplate = require('app/dynamic-template.html');  // Inline template here

=>

http://localhost:3000/main.bundle.js:

/***/ "./src/app/dynamic-template.html":
/***/ function(module, exports) {
module.exports = "<div *ngIf=\"visible\">\r\n    10 Support of <b>componentTemplatePath</b> attribute\r\n</div>"
/***/ },
