### ISSUE TITLE
dynamic content can not display

### ISSUE THREAD

**Issue by isczhao** [apoterenko/angular2-dynamic-component#22]
Running on the browser is no problem，
but， Mac virtual machine is NG..
use command: ionic emulate ios 
source:
1: ts file
`
public outerDynamicModules = [DynamicComponentModule];

    public outerDynamicContext = {
        innerDynamicContext: {},
        innerDynamicTemplate: ``,
        innerDynamicModules: [
            FormsModule
        ]
    };
    public outerDynamicTemplate = `
        <DynamicComponent [componentContext]='innerDynamicContext' 
                          [componentModules]='innerDynamicModules'
                          [componentTemplate]='innerDynamicTemplate'>         
        </DynamicComponent>
   `;
.....
this.outerDynamicContext.innerDynamicTemplate = data.content;
`
2: html
`<template dynamic-component (dynamicComponentReady)="dynamicCallback($event)" [componentContext]="outerDynamicContext" [componentModules]="outerDynamicModules" [componentTemplate]="outerDynamicTemplate"></template>`

**Comment by apoterenko** [comment]
Please check out the latest version

**Comment by apoterenko** [comment]
Please let me know, if you have some changes
