### ISSUE TITLE
DynamicComponent inside a Component that is used in a template for another Dynamic component doesn't work. Nothing is rendered, no errors

### ISSUE THREAD

**Issue by KeksKlip** [apoterenko/angular2-dynamic-component#23]
I use a dynamic component inside a Component A.
When the component A is rendered in a application component it works well.
But when I put the component A in a template for another dynamic component nothing is rendered,

I put my component a in a module (moduleB) and provide it to dynamic component with the FormModule,
dynamicExtraModules = [FormsModule, moduleB]
But it still does not work.

**Comment by apoterenko** [comment]
Try 1.2.0

See https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts

**Comment by apoterenko** [comment]
Fixed
