### ISSUE TITLE
DynamicComponent is part of the declarations of 2 modules: DynamicComponentModule and DynamicComponentFactoryModule! 

### ISSUE THREAD

**Issue by KeksKlip** [apoterenko/angular2-dynamic-component#25]
After update to 1.2.0 I get this error.
I use angular-cli

`DynamicComponent is part of the declarations of 2 modules: DynamicComponentModule and DynamicComponentFactoryModule! Please consider moving DynamicComponent to a higher module that imports DynamicComponentModule and DynamicComponentFactoryModule. You can also create a new NgModule that exports and includes DynamicComponent then import that NgModule in DynamicComponentModule and DynamicComponentFactoryModule.`

**Comment by apoterenko** [comment]
Try 1.3.2

**Comment by KeksKlip** [comment]
I've just tried it.
Same error

**Comment by KeksKlip** [comment]
`ng build --aot`  says that `"ERROR in DynamicComponentModule is not an NgModule"`

**Comment by apoterenko** [comment]
It's implementation restriction.

Need use only Module or Factory

See https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts

**Comment by KeksKlip** [comment]
So the paragraph 4 doesn't work any more?

> import {DynamicComponentModule} from 'angular2-dynamic-component/index';
> 
> @NgModule({
>     imports: [DynamicComponentModule]
> })

**Comment by apoterenko** [comment]
Works only one of them at the same time

**Comment by KeksKlip** [comment]
It seems that it doesn't work with angular-cli

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DYNAMIC_MODULE in...

**Comment by KeksKlip** [comment]
And I still get error 
`DynamicComponentModule is not an NgModule`
when I use only 

```
import {DynamicComponentModule} from 'angular2-dynamic-component/index';

@NgModule({
imports: [DynamicComponentModule]
})
```

without factory, and without any additional modules.

**Comment by KeksKlip** [comment]
Eventually I run my code.
I double checked that I use DynamicComponentModule everywhere.
It throws the error `DynamicComponentModule is not an NgModule` but I ignore it 
and It works. 

Thanks.

**Comment by apoterenko** [comment]
> It throws the error DynamicComponentModule is not an NgModule but I ignore it

I will check it using cli later

**Comment by apoterenko** [comment]
Try 1.0.0-beta.21 (it's work fine)

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@1.0.0-beta.21

C:\Windows\SysWOW64>ng --version
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

**Comment by apoterenko** [comment]
I have closed it. If you have some other issue, please let me know
