### ISSUE TITLE
Make it work with Angular Cli

### ISSUE THREAD

**Issue by ehsaanwelcome** [apoterenko/angular2-dynamic-component#26]
Hi,
I am unable to integrate with angular cli.
which js file, do i have to add in scripts tag of angular-cli.json?
thanks

**Comment by apoterenko** [comment]
What issue do you have?
Please provide error log

**Comment by dsl-src** [comment]
ERROR in DynamicComponentModule is not an NgModule
`
import {DynamicComponentModule} from 'angular2-dynamic-component/index';

@NgModule({
    imports: [DynamicComponentModule]
})
`

**Comment by apoterenko** [comment]
Try 1.0.0-beta.21 (it's work fine)

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@1.0.0-beta.21

C:\Windows\SysWOW64>ng --version
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

**Comment by dsl-src** [comment]
My angular cli latest is 1.0.0-beta.24

**Comment by javist7** [comment]
I got the same error in angular cli latest 1.0.0-beta.24, and angular cli latest 1.0.0-beta.21

**Comment by figuerres** [comment]
@apoterenko   I am also trying to solve this issue.
on the current angular-cli this stops the build of an app.
I am trying to use / update a project the author has not updated several months my start of a fork is here:
[https://github.com/figuerres/ng-busy](url)

I am in the process of learning how to build angular packages,  from what i have learned so far the one of the issues is that your package is built with TSC  and that does not create a metadata.json file that angular-cli needs for the AOT build process, if you switch to the NGC compiler that works with the angular platform it should create the metadata file that is currently missing.

there may be other issues but that seems to be the main one.

**Comment by apoterenko** [comment]
I am not sure that it will help but you may try 1.3.12. At this version, the module has been again compiled using ngc

**Comment by apoterenko** [comment]
> if you switch to the NGC compiler that works with the angular platform it should create the metadata file that is currently missing.

I know. But last time that is not helped me.

**Comment by figuerres** [comment]
thanks, i will check it out and let you know !

**Comment by apoterenko** [comment]
Guys, check out the beta-26

```
P:\tmp>ng --version

angular-cli: 1.0.0-beta.26
node: 6.9.1
os: win32 x64
```

It is working correctly now jointly with angular2-dynamic-component@1.3.12 

```
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-dynamic-component": "^1.3.12",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "ts-metadata-helper": "0.0.4",
    "zone.js": "^0.7.2"
  },
```

**Comment by figuerres** [comment]
@apoterenko  thanks!!!  just a note to confirm that i was able to use the updated package with my local test and it builds and runs w/o any sigh of error!
