### ISSUE TITLE
[Error] Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'.

### ISSUE THREAD

**Issue by dsoldera** [apoterenko/angular2-dynamic-component#27]
Hello,

I´m having this error on installation/ import on my project this plugin. Could anyone help me???

![error-plugin-angular2-dynamic](https://cloud.githubusercontent.com/assets/11474555/21463428/36494958-c950-11e6-98b3-a218b0293ec6.png)

**Comment by apoterenko** [comment]
Hi!

You should install

    "ts-metadata-helper": "0.0.3",
    "angular2-dynamic-component": "0.0.50"

or replace this one with the componentContext attribute as indicated below:

<DynamicComponent
          [componentContext]="{contextValue: 100500}"...>

**Comment by dsoldera** [comment]
Works great!!! Thank you very much!! =)
