### ISSUE TITLE
Another component in template doesn't work

### ISSUE THREAD

**Issue by javist7** [apoterenko/angular2-dynamic-component#28]
I cloned demo project, and added custom component (HomeTabsComponent with selector a2-home-tabs). Then i added <a2-home-tabs> </a2-home-tabs> in  outerDynamicTemplate :

```
outerDynamicTemplate = `
        <DynamicComponent [componentContext]='innerDynamicContext' 
                          [componentModules]='innerDynamicModules'
                          [componentTemplate]='innerDynamicTemplate'>         
        </DynamicComponent>
        <br>
        <a2-home-tabs> </a2-home-tabs>
        Inner dynamic value [this is a part of outer dynamic template]: {{ innerDynamicContext.value }}
   `;
```

I got this error : 
```
EXCEPTION: Uncaught (in promise): Error: Template parse errors:
'a2-home-tabs' is not a known element:
1. If 'a2-home-tabs' is an Angular component, then verify that it is part of this module.
2. If 'a2-home-tabs' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
        </DynamicComponent>
        <br>
        [ERROR ->]<a2-home-tabs> </a2-home-tabs>
        Inner dynamic value [this is a part of outer dynamic template]"): dynamicComponentClass@6:8
Error: Template parse errors:
'a2-home-tabs' is not a known element: ...
```

**Comment by apoterenko** [comment]
Try this one

```
outerDynamicModules = [DYNAMIC_MODULE, MyModule];

@NgModule
MyModule {
  declarations: [YourComponent],
  exports: [YourComponent]
}
```

**Comment by javist7** [comment]
I created module 
```
@NgModule({
  declarations: [HomeTabsComponent],
  exports: [HomeTabsComponent]
})
```

But how i can include it in outerDynamicModules ?

**Comment by apoterenko** [comment]
You should fill up an outerDynamicModules array 

outerDynamicModules = [DYNAMIC_MODULE, HomeTabsComponentModule];

**Comment by javist7** [comment]
How i can name my module ?( to HomeTabsComponentModule)

**Comment by apoterenko** [comment]
Good

**Comment by javist7** [comment]
My custom component have @Output event. How i can listen this in component where i call to <template ...> </template> ?

**Comment by apoterenko** [comment]
It's not clear. Provide more info

**Comment by apoterenko** [comment]
You could use componentContext for this purposes and pass emitter as input parameter in dynamic template

**Comment by javist7** [comment]
```
@Component({
  selector: 'a2-home-tabs',
  template: `<span> hello from qwe component </span>`
})
export class HomeTabsComponent {
  @Output() myEvent = new EventEmitter();

  constructor() {
    this.myEvent.emit('qweasd2');
  }
}
```
```
outerDynamicTemplate = `
        <a2-home-tabs > </a2-home-tabs>
         `;
```

```
<template dynamic-component
              [componentContext]="outerDynamicContext"
              [componentModules]="outerDynamicModules"
              [componentTemplate]="outerDynamicTemplate"
              (myEvent) = "listener($event)"></template>
```

Error

```
Event binding myEvent not emitted by any directive on an embedded template. Make sure that the event name is spelled correctly and all directives are listed in the "directives" section. ("dules]="outerDynamicModules"
              [componentTemplate]="outerDynamicTemplate"
              [ERROR ->](myEvent) = "listener($event)"></template>
```

**Comment by javist7** [comment]
Where i can use this emitter ?

**Comment by javist7** [comment]
My AppComponent call to `<template dynamic-component ...> </template> ` where `[componentTemplate]`  have my custom component `HomeTabsComponent` which the have `@Output() myEvent = new EventEmitter()`. How i can call to function listener() (in my `AppComponent`) when in `HomeTabsComponent` `meEvent().emit();` ?

**Comment by apoterenko** [comment]
Something like that

<template componentContext='{callback: myCallback}' template='myTpl'></template>
myTpl= ' <a2-home-tabs (eventHandling)='myCallback($event)'> </a2-home-tabs>'
@Component
A2HomeTabs {
 @Output
 emitter = ...
}

AppComponent {
    myCallback = this.myCallback
}

**Comment by javist7** [comment]
Thank you very much for your help.

**Comment by javist7** [comment]
*ngIf , [ngClass] doesn't work in my <a2-home-tabs> component

**Comment by apoterenko** [comment]
Please provide source code here

**Comment by javist7** [comment]
```
outerDynamicTemplate = `
        <DynamicComponent [componentContext]='innerDynamicContext' 
                          [componentModules]='innerDynamicModules'
                          [componentTemplate]='innerDynamicTemplate'>         
        </DynamicComponent>
        <br>
        <a2-home-tabs> </a2-home-tabs>
          `;
```

a2-home-tabs template : 
`<spang *ngIf="true"> </span>`

My error

```
EXCEPTION: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngIf' since it isn't a known property of 'span'. ("<span [ERROR ->]*ngIf="true"> hello from nested component </span>"): ....
```

**Comment by apoterenko** [comment]
Try this one

```
import {CommonModule} from "@angular/common";

@NgModule
HomeTabsComponentModule {
   imports: [CommonModule]
}

outerDynamicModules = [DYNAMIC_MODULE, HomeTabsComponentModule];
```

**Comment by javist7** [comment]
You are my hero. Thanks

**Comment by jratiwanich** [comment]
Why I keep getting these errors when I try to do this in my child's component? I got it working find on my parent's component "AppComponent".


`Can't bind to 'componentType' since it isn't a known property of 'template'. ("
  <template dynamic-component
        *ngFor="let field of columns"
        [ERROR ->][componentType]="field.type"
        [componentContext]="field.context">
  </template>
"): dynamicComponentClass@4:8
Can't bind to 'componentContext' since it isn't a known property of 'template'. ("
        *ngFor="let field of columns"
        [componentType]="field.type"
        [ERROR ->][componentContext]="field.context">
  </template>
</div>
"): dynamicComponentClass@5:8`

**Comment by apoterenko** [comment]
You should pass the module to your child component.

 [componentModules] = [DynamicComponentModule];

See
https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts#L59

**Comment by apoterenko** [comment]
Unfortunately, by default, injecting modules does not work recursively in Angular. You should care about this manually. 

For example, I should pass CommonModule itself

https://github.com/apoterenko/angular2-dynamic-component/blob/master/src/DynamicBase.ts#L234

**Comment by jratiwanich** [comment]
Thank you!!
Can we pass the json object instead of a module recursively? 
e.g. 
[componentType]="myParentComponent"
[componentContext]="myParentJsonObject"

[componentType]="myChildComponent"
[componentContext]="myChildJsonObject"


myParentComponent template will create "myChildComponent" and will have another <template dynamic-component ...> to create another child component and so on.

**Comment by apoterenko** [comment]
Sorry, I do not understand the problem. Yes, you can deliver the outer objects to objects on any inner level manually

**Comment by jratiwanich** [comment]
Here is my example with code. Basically it's a nested template inside another template.

```
@Component({
template: '<template dynamic-component
            *ngFor="let field of columns"
            [componentType]="field.type"
            [componentContext]="field.context">
          </template>'
...
}
export class AppComponent implements OnInit {
...
// Scenario #3 {No 9}
  columns = [{
    type: Child1Component,
    context: {
      fieldName: 'description',
      value: 'Test description'
    }
  }, 
  {
    type: Child2Component,
    context: {
      fieldName: 'expired',
      value: true
    }
  }
  }];
...
...
}
///////////////////////////////////////////
//in the child component - I have another template list another child component
...
@Component({
template: '<template dynamic-component
            *ngFor="let field of childList"
            [componentType]="field.type"
            [componentContext]="field.context">
          </template>'
...
}
export class Child1Component {
  @Input() fieldName: string;
  @Input() value: boolean;
  childList = [ 
  {
    type: Child2Component,
    context: {
      fieldName: 'expired',
      value: true
    }, ...
  }...
  }];
}
....
    
```
When I do this, I'm getting a run-time error in the Child1Component below.
*If I remove the template in the Child1Component, everything is working fine. I only see the error when I try a nested component.

```
`Can't bind to 'componentType' since it isn't a known property of 'template'. ("
<template dynamic-component
*ngFor="let field of columns"
[ERROR ->][componentType]="field.type"
[componentContext]="field.context">

"): dynamicComponentClass@4:8
Can't bind to 'componentContext' since it isn't a known property of 'template'. ("
*ngFor="let field of columns"
[componentType]="field.type"
[ERROR ->][componentContext]="field.context">
"): dynamicComponentClass@5:8`
```

**Comment by apoterenko** [comment]
```
export const DYNAMIC_MODULE = DynamicComponentModuleFactory.buildModule([ /** Custom modules here **/ ]);

@Component({
template: '<template dynamic-component
            *ngFor="let field of columns"
            [componentType]="field.type"
            [componentModules] = 'extraModules'
            [componentContext]="field.context">
          </template>'
...
}
export class AppComponent implements OnInit {
   extraModules = [DYNAMIC_MODULE];
```

**Comment by jratiwanich** [comment]
Still getting the same errors after i follow your demo code. Do I need to upgrade to Angular4?

```
npm ERR! peer dep missing: @angular/common@~4.0.0-rc.4, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: @angular/compiler@~4.0.0-rc.4, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: @angular/core@~4.0.0-rc.4, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: @angular/http@~4.0.0-rc.4, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: @angular/platform-browser@~4.0.0-rc.4, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: rxjs@~5.0.2, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: typescript@^2.1.5, required by @angular/tsc-wrapped@4.1.1
npm ERR! peer dep missing: zone.js@~0.8.4, required by angular2-dynamic-component@1.5.1
npm ERR! peer dep missing: typescript@^2.1.0, required by tsickle@0.21.6
npm verb exit [ 1, true ]
```

**Comment by apoterenko** [comment]
Check out 1.5.2

**Comment by jratiwanich** [comment]
I will try the new demo this weekend. No time to work on it right now. Thank you for fixing it so quickly!

**Comment by jratiwanich** [comment]
Got it to work with ng4 and Scenario#5 now. Thank again you for fixing this so quickly. I will keep on testing it. So I assume this test case will not work with ng2 package.
