### ISSUE TITLE
Dynamic component Security Recommendations

### ISSUE THREAD

**Issue by jorgepluna** [apoterenko/angular2-dynamic-component#29]
I use your software successfully.  Do you have any concerns with security? I generate the template dynamically from a .NET Server on the cloud. The template is not generated as per user input. Is only generated based on a config file on the server. Then the dynamic component uses my server generated template. 

Any concerns you Have with possible attacks? 

Thanks

**Comment by apoterenko** [comment]
At first, we must prevent the following attacks:

1. https://en.wikipedia.org/wiki/Cross-site_request_forgery
2. https://en.wikipedia.org/wiki/Cross-site_scripting

At second, Angular2 give us #2 solution out of the box when DOM-nodes to insert into the DOM (https://angular.io/docs/ts/latest/guide/security.html#!#xss).
The #1 attack must be fixed using tokens (request-response generated tokens) - you may pass token via @Inject Http.headers object (see https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Synchronizer_.28CSRF.29_Tokens)

**Comment by jorgepluna** [comment]
Thank you Alex.
