### ISSUE TITLE
Update peer dependencies to support later versions of angular

### ISSUE THREAD

**Issue by fallXone** [apoterenko/angular2-dynamic-component#30]
Right now, the peer dependencies are set to only use ~2.2.4

"@angular/core": "~2.2.4",
"@angular/common": "~2.2.4",
"@angular/compiler": "~2.2.4",
"@angular/platform-browser": "~2.2.4",
"@angular/http": "~2.2.4",

This causes issues in libraries that have this dependency, where the consumer of that library is using a version of angular higher than 2.2.4 which is fairly old. Specifically this has become a problem with this library which uses this package, https://github.com/devyumao/angular2-busy/issues/29

**Comment by apoterenko** [comment]
I have just now updated to 

  "peerDependencies": {
    "@angular/core": "~2.4.3",
    "@angular/common": "~2.4.3",
    "@angular/compiler": "~2.4.3",
    "@angular/platform-browser": "~2.4.3",
    "@angular/http": "~2.4.3",

Is that enough?

**Comment by chinra02** [comment]
After 1.3.10 update, i am getting below error

ERROR in [at-loader] node_modules\angular2-dynamic-component\DynamicBase.d.ts:1:1
    Cannot find type definition file for 'core-js'

**Comment by apoterenko** [comment]
Done (1.3.11)

**Comment by klihelp** [comment]
prepare for angular 4

**Comment by apoterenko** [comment]
I have made temporary workaround while https://github.com/angular/angular/issues/15241
