### ISSUE TITLE
Error: Unexpected value \'DynamicComponentModule\' imported  by the module

### ISSUE THREAD

**Issue by macdasi** [apoterenko/angular2-dynamic-component#31]
When I try to include it inside [angular2-seed](https://github.com/mgechev/angular-seed)
I get error 

> Error: Unexpected value \'DynamicComponentModule\' imported  by the module   

Does the package supports AoT ? I can manage to work with it in not AoT angular project .

**Comment by apoterenko** [comment]
Sorry, but the component does not support AoT mode.
See https://github.com/apoterenko/angular2-dynamic-component/issues/17

**Comment by macdasi** [comment]
Will it ?

**Comment by apoterenko** [comment]
An error has disappeared but still not working (1.3.13). Closed as duplicate
