### ISSUE TITLE
Using custom components

### ISSUE THREAD

**Issue by anrtero** [apoterenko/angular2-dynamic-component#32]
Is it possible to read DOM-element schema from main module? Or is it possible to define custom elements that can be used with dynamic components module. Currently I think there is no way to use for example Material Design for Angular 2 components with this dynamic components module. For example normal input elements can be used with no problems but when attempting to use md-input element occurs an error message that suggests to add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' which is already there but this module is not using that defination.

**Comment by apoterenko** [comment]
Hmm.. why not?

You may define your custom component and use them inside a dynamic component or do import third-party components. 

See 

https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts#L103

**Comment by anrtero** [comment]
Ohhh, nice! How could I miss that :) Thanks a lot!
