### ISSUE TITLE
Does this supports pipes in the template 

### ISSUE THREAD

**Issue by chinra02** [apoterenko/angular2-dynamic-component#33]
One of my template has custom pipes, Is there any way i can do this. I have tried using dynamicExtraModules , but no luck. Please let me know. Thanks

**Comment by apoterenko** [comment]
See 

https://github.com/apoterenko/angular2-dynamic-component/issues/32

**Comment by apoterenko** [comment]
Se 

https://github.com/apoterenko/angular2-dynamic-component/issues/28

**Comment by chinra02** [comment]
Thanks. That worked. Cool !!!!!
