### ISSUE TITLE
UMD bundle?

### ISSUE THREAD

**Issue by BrianWalters** [apoterenko/angular2-dynamic-component#34]
The "main" property in package.json references a UMD bundle which would work great for my pipeline but I can't find it in the repo or the node package directory. Do I have to build this myself? Any easier way then to copy the whole package?

**Comment by apoterenko** [comment]
Check out 1.3.14

**Comment by BrianWalters** [comment]
Works for me now. Thanks dude! Does that UMD include the dep "ts-metadata-helper"?

**Comment by apoterenko** [comment]
Try this one: 1.3.15
This version contains full bundle without extra dependencies except as Angular2 dependency

**Comment by apoterenko** [comment]
Please let me know if you have some other questions.

**Comment by BrianWalters** [comment]
We got your new bundle and it's all working smoothly in our project. We're using this component as a ng-include but for Angular 2. Thanks for making this!
