### ISSUE TITLE
 Possible to pass a component and it's corresponding module?

### ISSUE THREAD

**Issue by chinra02** [apoterenko/angular2-dynamic-component#35]
IS it possible to pass a component and its corresponding module, instead of template and context data, So that component can handle the context data and all the actions that's happening on the components.

**Comment by apoterenko** [comment]
That should works ([componentType]="YOUR_TYPE").

See https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts

**Comment by chinra02** [comment]
Thanks for your quick response. I noticed with this approach, services that were injected into the component is not getting passed in and overwritten by ElementRef. Is there any to retain the services as it is?

**Comment by apoterenko** [comment]
Check out 1.5.1

For example:

```
@Component({
	template: `<input name="{{fieldName}}" type="text" [value]="value">`,
})
export class TextField {
	@Input() fieldName: string;
	@Input() value: string;

	constructor(
	    private appState: AppState,
	    private elementRef: ElementRef,
	    private appRef: ApplicationRef
	) {
		console.log('The TextField constructor has been called');
	}

	ngOnInit() {
		setTimeout(() => this.value = this.fieldName + ': next value', 4000);
		this.elementRef.nativeElement.childNodes[0].style.color = 'red';
	}
}
```

**Comment by chinra02** [comment]
Hey, Cool I am not getting any errors, but one thing i am noticing here is Component is not getting updated when i change the Object that's been referenced in the template, to fix this i thought of using the push strategy, when i used changeDetectorRef for that, I am getting no provider for  changeDetectorRef Error. Any idea how this can be solved?

**Comment by apoterenko** [comment]
Can you provide the example?

In this case, the component has getting updated. 

```
/*
 * App Component
 * Top Level Component
 */
@Component({
  selector: 'app',
  template: `
    <main>
      <router-outlet></router-outlet>
    </main>
   
    <template dynamic-component
          *ngFor="let field of columns"
          [componentType]="field.type"
          [componentContext]="field.context">
    </template>
  `
})
export class AppComponent implements OnInit {
  
  columns = [{
    type: TextField,
    context: {
      fieldName: 'description',
      value: 'Test description',
      object: {}
    }
  }];
  
  ngOnInit() {
    let initialValue = 0;

    setInterval(() => {
      Reflect.set(this.columns[0].context, 'object', {
        xxx: '666' + initialValue
      });
    }, 1000);
  }
}
```

```
@Component({
  template: `{{object.xxx}}`,
})
export class TextField {
  @Input() fieldName: string;
  @Input() value: string;
  @Input() object: {};

  constructor(private appState: AppState, private elementRef: ElementRef, private renderer: Renderer) {
    console.log('The constructor of TextField is called', this.appState);  // The constructor of TextField is called
  }

  ngOnInit() {
    this.elementRef.nativeElement.childNodes[0].style.color = 'red';
    this.appState.set('value', '100500');
  }
}
```

**Comment by apoterenko** [comment]
It's very important to pass initial structure like this

columns = [{
    context: {
      fieldName: 'description',     // @Input 1st FIELD
      value: 'Test description',     // @Input 2st FIELD
      object: {}                           // !! EMPTY INITIAL STATE
    }
  }];

**Comment by chinra02** [comment]
Thanks a lot for your help, I am seeing weird behavior, not sure it's from angular side. I have a huge component tree, at the leaf component i have this dynamic component. Parent component is following the push strategy and so some how dynamic component is only working if that is also a push strategy. if not, if I mouseover on the dynamic component, then  it's is getting updated. So the data binding is happening but the change detection is not getting triggered.

So i fixed it by passing the changeDetector instance to the dynamic component through input data bind (Same like fieldName) and triggering the changeDetection in the code manually works.

One more thing i noticed ngOnInit() method is called twice for every time component is getting loaded.

**Comment by apoterenko** [comment]
I get it.

> One more thing i noticed ngOnInit() method is called twice for every time component is getting loaded.

In this case  ngOnDestroy()  should be called twice too. If so there is no unexpected behaviour because see

https://github.com/apoterenko/angular2-dynamic-component/blob/master/src/DynamicBase.ts#L111

You call changeDetection manually, therefore DynamicComponent is destroyed an internal instance of your component.

Also you can append console.log to js code (node_modules/angular2-dynamic-component/DynamicBase.js) for local debugging

**Comment by apoterenko** [comment]
> TypeError: Reflect.get cal…, rejection: TypeError: Reflect.get called on non-objec

A component context should always have Object type

@Input() componentContext: ComponentContext;

**Comment by chinra02** [comment]
Thanks a lot for your help. Looks like one of the templates had an issue, no more errors after fixing that. 

You are awesome 👍

**Comment by hiepnguyen93** [comment]
Hi, I define `DynamicComponentModule` in App.Module and then I define `export const DYNAMIC_MODULE = DynamicComponentModuleFactory.buildModule([AppModule]);`. 
It got an error 
`EXCEPTION: Uncaught (in promise): Error: Type DynamicComponent is part of the declarations of 2 modules: DynamicComponentModule and DynamicComponentFactoryModule! Please consider moving DynamicComponent to a higher module that imports DynamicComponentModule and DynamicComponentFactoryModule. You can also create a new NgModule that exports and includes DynamicComponent then import that NgModule in DynamicComponentModule and DynamicComponentFactoryModule.`
Any idea how this can be solved?

**Comment by apoterenko** [comment]
Hi, see here

https://github.com/apoterenko/angular2-dynamic-component/issues/25
