### ISSUE TITLE
Unable to build product In angular cli

### ISSUE THREAD

**Issue by hiepnguyen93** [apoterenko/angular2-dynamic-component#36]
Hi, I'm using angular 2.4.8,
I declare in main module 
import { DYNAMIC_MODULE } from './dynamic.module';
@NgModule({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  ...
  imports: [
  ...
    DynamicTemplateModule.forRoot(),
    DYNAMIC_MODULE
  ],
  providers: [
})
In './dynamic.module': 
export const DYNAMIC_MODULE = DynamicComponentModuleFactory.buildModule([DynamicTemplateModule]);
I run in Dev mode but when I build product it Show an error:
![image](https://cloud.githubusercontent.com/assets/24579838/24606820/1e018476-1899-11e7-85a5-e39e0dbb5ccd.png)
Can you help to check it

**Comment by apoterenko** [comment]
Try to build directly


```
import {DynamicCache, DynamicComponent, DynamicDirective, DYNAMIC_TYPES} from "angular2-dynamic-component";

@NgModule(
			{
				providers: [
					DynamicCache,
					{provide: DYNAMIC_TYPES.DynamicExtraModules, useValue: DynamicTemplateModule}
				],
				declarations: [
					DynamicComponent,
					DynamicDirective
				],
				exports: [
					DynamicComponent,
					DynamicDirective
				]
			}
		)
		class DYNAMIC_MODULE {
		}
```

**Comment by hiepnguyen93** [comment]
Ok, it's good, thanks so much.
  I have another issue: I have a component Home, then I load dynamic template for it. In that template, I've child Component and it should load dynamic template too. 
  In home component I define 
  ```
<DynamicComponent [componentContext]='{root: root}' [componentModules]='moduleTemplate' [componentTemplate]='template'>
</DynamicComponent>
```
 In child component I define the same with Home Component. But when I run It show error 
![image](https://cloud.githubusercontent.com/assets/24579838/24639509/3fe15fa4-191a-11e7-80a2-5756e1496961.png)

**Comment by apoterenko** [comment]
useValue: [DynamicTemplateModule]
