### ISSUE TITLE
Angular 4.9

### ISSUE THREAD

**Issue by jorgepluna** [apoterenko/angular2-dynamic-component#37]
Can we us it with Angular 4.0???  Thanks

**Comment by apoterenko** [comment]
Why not??

**Comment by apoterenko** [comment]
See README

**Comment by jorgepluna** [comment]
I was just wondering if you have any dependencies with Angular 2.0 or other packages? Thanks

**Comment by hiepnguyen93** [comment]
Hi Bro,
I'm using angular 4.0.2.  I define a dymamicModule 

`@NgModule({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [...],
  declarations: [.... DynamicComponent, DynamicDirective],
  exports: [.... DynamicComponent, DynamicDirective],
  providers: [
	DynamicCache,
	{provide: DYNAMIC_TYPES.DynamicExtraModules, useValue: dynamicExtraModules}]}
` 
Then I run and it got error 
![image](https://cloud.githubusercontent.com/assets/24579838/25268790/4da27a3c-26a4-11e7-8302-1ca61541accd.png)

Please help me to check it, Thanks so much

**Comment by apoterenko** [comment]
dynamicExtraModules should be an array

**Comment by hiepnguyen93** [comment]
`{provide: DYNAMIC_TYPES.DynamicExtraModules, useValue: dynamicExtraModules}`
What should I define in this provider?? Is it my define module?

**Comment by apoterenko** [comment]
https://github.com/apoterenko/angular2-dynamic-component/blob/master/src/DynamicComponentModule.ts#L37

{provide: DYNAMIC_TYPES.DynamicExtraModules, useValue: []}

**Comment by apoterenko** [comment]
try this one

**Comment by apoterenko** [comment]
DynamicComponentModuleFactory.buildModule([])

**Comment by hiepnguyen93** [comment]
great, Thank you so much =)). Problem resoled when I add that module to array
