### ISSUE TITLE
Angular 4 ngComponentOutlet vs angular-dynamic-component

### ISSUE THREAD

**Issue by jorgepluna** [apoterenko/angular2-dynamic-component#38]
Questions: We tried to use Angular 4 ngComponentOutlet. However the content options does not appear to have the context available for the js. 

Can we replicate all functionality from this package into ngComponentOutlet Angular 4.

Thanks Alex (great job you have done!)

**Comment by apoterenko** [comment]
You can use this library in future as well. 
Unfortunately, ngComponentOutlet contains only 50% entire functionality.
