### ISSUE TITLE
Any plans to upgrade to angular 4?

### ISSUE THREAD

**Issue by chinra02** [apoterenko/angular2-dynamic-component#39]
Any plans to upgrade to angular 4?

**Comment by apoterenko** [comment]
Hi! Yeah, sure

https://github.com/apoterenko/angular2-dynamic-component/blob/master/package.json#L24

**Comment by apoterenko** [comment]
Try 1.5.2

**Comment by apoterenko** [comment]
Do you want rename the library? Aka ngx-dynamic?

**Comment by apoterenko** [comment]
I can do that, if you want..

**Comment by chinra02** [comment]
Ya, Lets follow angular pattern same as ngx- dynamic, Thanks for the quick reply!!

**Comment by Meligy** [comment]
Hello.

This looks awesome :) -- Is Angular 4.0 Final supported? 4.1?

Thanks a lot.

Cheers,

**Comment by apoterenko** [comment]
Hi there! 
Check out 1.6.1

**Comment by chinra02** [comment]
I will check it and Thanks for the quick update. :+1:

**Comment by apoterenko** [comment]
Renaming has been done also. Thanks for the request

**Comment by apoterenko** [comment]
Check out 2.1.5
