### ISSUE TITLE
[default] /node_modules/angular2-dynamic-component/DynamicComponent.d.ts:1:19  Module '"/node_modules/@angular/core/index"' has no exported member 'ComponentMetadataType'.

### ISSUE THREAD

**Issue by lwensveen** [apoterenko/angular2-dynamic-component#4]
I think this is due to the upgrade to RC7? See https://github.com/angular/angular/commit/63e15ff

EDIT: I've cloned the repo and taken a look. It seems that the ComponentMetadataType and InputMetadata in the DynamicComponent.ts are causing problems. I can't test or deploy the app so you'll probably have to do that.

**Comment by apoterenko** [comment]
See 0.0.40 build. It should work fine (using Angular2.0.0)
