### ISSUE TITLE
swapping componets in an out causes declarations of 2 modules

### ISSUE THREAD

**Issue by dsoltesz** [apoterenko/angular2-dynamic-component#5]
depending on which page or some condition, I want to load the component dynamicly.  Go to first page, GreenButton loads, go to 2nd page, YellowButton loads, return to first page Error 

 **Type GreenButton is part of the declarations of 2 modules: dynamicComponentModule and dynamicComponentModule! ; Zone: angular ; Task: Promise.then ; Value: Error: Type GreenButton is part of the declarations of 2 modules:**

`get settingsComponent() {
        if(someVluae)
            return YellowButton;

        return GreenButton;
    }`

**Comment by apoterenko** [comment]
Please provide more info, codes

**Comment by apoterenko** [comment]
Thanks!

I have fixed. Check 0.0.45..
