### ISSUE TITLE
How to work with Directives without Modules

### ISSUE THREAD

**Issue by zymmotic** [apoterenko/angular2-dynamic-component#6]
Thank you, it's work!
But when i use implementation of [wysiwyk editor](https://github.com/froala/angular2-froala-wysiwyg) that haven't module, only directives, i get an error.
_Can't bind to 'froalaEditor' since it isn't a known property of 'div'_
I can't add module to [componentModules], what can i do?

**Comment by zymmotic** [comment]
I wrote previous issues and found answer.
Amazing component. Thank you!

**Comment by WinsonSoo** [comment]
Hi,
I have the similar issue!
I manage to display the editor in mainpage (app/app.html), but unable to display it on other page (say contentPage). May I know how do you solve the error?

**Comment by asantainnasa** [comment]
WinsonSoo, are you using lazy loading?
If so, make sure to add the module imports into the module.ts for each page you want the editor on. 

```
// Import Froala Editor.
import "froala-editor/js/froala_editor.pkgd.min.js";

// Import Angular2 plugin.
import { FroalaEditorModule, FroalaViewModule } from 'angular-froala-wysiwyg';
...

@NgModule({
   ...
   imports: [FroalaEditorModule.forRoot(), FroalaViewModule.forRoot() ... ],
   ...
})
```
