### ISSUE TITLE
Is it possible to insert DynamicComponentModule into itself?

### ISSUE THREAD

**Issue by Djosani** [apoterenko/angular2-dynamic-component#7]
Is it possible to insert DynamicComponent tag into other DynamicComponent tag? When i add DynamicComponentModule to extraModules i have nothing.

**Comment by apoterenko** [comment]
I am not able to quickly fix this issue. But, I think it is a valid point

**Comment by zymmotic** [comment]
Ok.
Helpful component, thank you.

**Comment by apoterenko** [comment]
See 1.0.1, Feature #4 

This is a combination of dynamic-directive & DynamicComponent, therefore it works fine.

**Comment by apoterenko** [comment]
Try 1.2.0

See https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts
