### ISSUE TITLE
Cannot resolve module 'ts-metadata-helper/index'

### ISSUE THREAD

**Issue by charliebrink** [apoterenko/angular2-dynamic-component#8]
I get error 'Cannot resolve module 'ts-metadata-helper/index' in ../node_modules/angular2-dynamic-component @ ./~/angular2-dynamic-component/DynamicComponent.js 14:14-49'

**Comment by apoterenko** [comment]
Try to install it

npm install ts-metadata-helper --save

**Comment by scottopolis** [comment]
I also had this issue, I had to install core-js first:

npm install core-js@~2.4.0 --save
npm install ts-metadata-helper --save

Works now.

**Comment by apoterenko** [comment]
Yeah. Unfortunately, but the component is dependent on other modules... 

``
  "peerDependencies": {
  ..
    **"core-js": "~2.4.0"**
    **"ts-metadata-helper": "~0.0.3"**
  ..
  }
``

npm manager shows the unresolved peer dependencies when you install the target package

**Comment by scottopolis** [comment]
@apoterenko BTW, thanks so much for this project, it works perfect for what I need :)

**Comment by apoterenko** [comment]
Thanks! I am glad that the module is useful for other developers)

**Comment by apoterenko** [comment]
I have updated README at 0.0.51

**Comment by charliebrink** [comment]
Thanks, working for me too now.
